// Reads the URLs and keys of the running local Supabase instance, so no local
// credential is ever typed into a file by hand or committed.
//
//   node scripts/local-env.mjs --write          create .env.local (never overwrites)
//   node scripts/local-env.mjs --exec node <script> [args...]
//                                               run a Node entry point with the local env set
//
// The keys the CLI reports are Supabase's published local development keys.
// They grant nothing outside the Docker containers on this machine.
import { spawn, spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPOSITORY_ROOT = fileURLToPath(new URL("..", import.meta.url));
const SUPABASE_CLI = fileURLToPath(
  new URL("../node_modules/supabase/dist/supabase.js", import.meta.url),
);

export function localSupabaseStatus() {
  const result = spawnSync(
    process.execPath,
    [SUPABASE_CLI, "status", "--output", "json"],
    { cwd: REPOSITORY_ROOT, encoding: "utf8" },
  );
  // The CLI pretty-prints the JSON across lines, after any status messages.
  const stdout = result.stdout ?? "";
  const start = stdout.indexOf("{");
  const end = stdout.lastIndexOf("}");
  const json = start === -1 || end < start ? "" : stdout.slice(start, end + 1);

  if (result.status !== 0 || !json) {
    throw new Error(
      "Local Supabase is not running. Start it with `pnpm supabase:start` (Docker must be running).",
    );
  }

  const status = JSON.parse(json);
  for (const key of ["API_URL", "ANON_KEY", "SERVICE_ROLE_KEY"]) {
    if (typeof status[key] !== "string" || status[key] === "") {
      throw new Error(`\`supabase status\` did not report ${key}`);
    }
  }

  // Everything that uses this — .env.local, the real-Supabase suites, the
  // Playwright launcher — creates users and sends mail. It must only ever
  // reach this machine, whatever the CLI or its configuration reports.
  const { hostname } = new URL(status.API_URL);
  if (!LOOPBACK_HOSTS.has(hostname)) {
    throw new Error(
      `Refusing to use Supabase at ${hostname}: only a local instance is allowed.`,
    );
  }
  return status;
}

const LOOPBACK_HOSTS = new Set(["127.0.0.1", "localhost", "[::1]"]);

/**
 * The application's environment against local Supabase. Values that do not
 * come from Supabase are placeholders that reach no real service.
 */
export function localAppEnv({ appUrl = "http://localhost:3000" } = {}) {
  const status = localSupabaseStatus();
  return {
    NEXT_PUBLIC_APP_URL: appUrl,
    SUPABASE_URL: status.API_URL,
    SUPABASE_ANON_KEY: status.ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: status.SERVICE_ROLE_KEY,
    STRIPE_SECRET_KEY: "sk_test_local_placeholder",
    STRIPE_WEBHOOK_SECRET: "whsec_local_placeholder",
    CRON_SECRET: "local-placeholder-cron-secret-of-sufficient-length",
    LOG_LEVEL: "warn",
    // For suites that read mail: Mailpit's HTTP API.
    LOCAL_MAILPIT_URL: status.MAILPIT_URL ?? status.INBUCKET_URL ?? "",
  };
}

function writeEnvLocal() {
  const target = `${REPOSITORY_ROOT}.env.local`;
  if (existsSync(target)) {
    console.error(".env.local already exists; not overwriting it.");
    process.exit(1);
  }
  const { LOCAL_MAILPIT_URL: _mailpit, ...env } = localAppEnv();
  const body = Object.entries(env)
    .map(([name, value]) => `${name}=${value}`)
    .join("\n");
  writeFileSync(
    target,
    `# Generated by scripts/local-env.mjs from \`supabase status\`.\n${body}\n`,
  );
  console.error("Wrote .env.local for local Supabase.");
}

function execWithEnv(command) {
  // Only `node <script> ...` is accepted. Spawning through a shell would join
  // the arguments unquoted on Windows, and pnpm's .cmd shims cannot be spawned
  // without one — so callers name a Node entry point directly.
  if (command[0] !== "node" || command.length < 2) {
    console.error(
      "Usage: node scripts/local-env.mjs --exec node <script> [args...]",
    );
    process.exit(1);
  }
  const child = spawn(process.execPath, command.slice(1), {
    stdio: "inherit",
    cwd: REPOSITORY_ROOT,
    env: { ...process.env, ...localAppEnv() },
  });
  child.on("exit", (code) => process.exit(code ?? 1));
}

const USAGE = `Usage:
  node scripts/local-env.mjs --write
  node scripts/local-env.mjs --exec node <script> [args...]`;

// Run as a script, not when imported by the Playwright launcher.
const invokedDirectly =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  const [mode, ...rest] = process.argv.slice(2);
  if (mode === "--write") {
    writeEnvLocal();
  } else if (mode === "--exec") {
    execWithEnv(rest);
  } else {
    // A mistyped mode must fail, or a test step would pass having run nothing.
    console.error(USAGE);
    process.exit(1);
  }
}
